#!/bin/bash

until /home/pi/go/src/github.com/bryandowen/gohottub/gohottub > /var/log/gohottub/gohottub-$(date +%s).log; do
	echo "GoHotTub crashed with exit code $?. Respawning..." >> /var/log/gohottub/gohottub.log
	sleep 1
done

