#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root. Please try again with 'sudo $0'."
	exit 1
else
	echo "/var/log/gohottub/*.log {" >> /etc/logrotate.conf
	echo "        weekly" >> /etc/logrotate.conf
	echo "        missingok" >> /etc/logrotate.conf
	echo "        rotate 4" >> /etc/logrotate.conf
	echo "        delaycompress" >> /etc/logrotate.conf
	echo "        notifempty" >> /etc/logrotate.conf
	echo "}" >> /etc/logrotate.conf
fi
