#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root. Please try again with 'sudo $0'."
	exit 1
else
	htPID=$(ps aux | grep 'start' | grep 'HotTub' | awk '{print $2}')
	kill -9 $htPID
	htPID2=$(ps aux | grep '[p]ython' | grep 'HotTub' | awk '{print $2}')
	kill -9 $htPID2
	sleep 1
	htPID3=$(ps aux | grep '[p]ython' | grep 'HotTub' | awk '{print $2}')
	if [[ $htPID3 -ne "" ]]; then
		echo Looks like it did not die.
	else
		echo Process killed.
	fi
fi
